// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRxU9qq8epzJzNBw3g4D7MOuxfV6a4G9I',
    appId: '1:253343347002:web:e64df53ad02341cffae003',
    messagingSenderId: '253343347002',
    projectId: 'healthtip-8e5d8',
    authDomain: 'healthtip-8e5d8.firebaseapp.com',
    storageBucket: 'healthtip-8e5d8.firebasestorage.app',
    measurementId: 'G-DHZQQ3WSZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjX6HGsNTap0Jqxf1Nvbp-dLMHTpf2_TA',
    appId: '1:253343347002:android:a4be555ffd62f962fae003',
    messagingSenderId: '253343347002',
    projectId: 'healthtip-8e5d8',
    storageBucket: 'healthtip-8e5d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYTCLm7eoObuM_V-AbZ8bq7L83y1vzDVg',
    appId: '1:253343347002:ios:de9f2194e88703f7fae003',
    messagingSenderId: '253343347002',
    projectId: 'healthtip-8e5d8',
    storageBucket: 'healthtip-8e5d8.firebasestorage.app',
    iosBundleId: 'com.example.healthTipApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYTCLm7eoObuM_V-AbZ8bq7L83y1vzDVg',
    appId: '1:253343347002:ios:de9f2194e88703f7fae003',
    messagingSenderId: '253343347002',
    projectId: 'healthtip-8e5d8',
    storageBucket: 'healthtip-8e5d8.firebasestorage.app',
    iosBundleId: 'com.example.healthTipApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRxU9qq8epzJzNBw3g4D7MOuxfV6a4G9I',
    appId: '1:253343347002:web:0275b43a1f2c5490fae003',
    messagingSenderId: '253343347002',
    projectId: 'healthtip-8e5d8',
    authDomain: 'healthtip-8e5d8.firebaseapp.com',
    storageBucket: 'healthtip-8e5d8.firebasestorage.app',
    measurementId: 'G-LZV6HXFKWP',
  );
}
